[package]
name = "rlreplay_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "rlreplay_rust"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "abi3-py38"] }
boxcars = "0.10.7"

[package.metadata.maturin]
name = "rlreplay_rust"
